name: DockerHub

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:

  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: downcase REPO
      run: |
        export REPO=${GITHUB_REPOSITORY,,}
        echo "REPO=${REPO}" >>${GITHUB_ENV}
        echo "REGISTRY_IMAGE=${REGISTRY}/${REPO}" >>${GITHUB_ENV}
        echo "IMAGE_NAME=${REPO}" >>${GITHUB_ENV}

    - name: Get util-linux version
      id: get_util_linux
      run: |
        version=$(curl --silent https://api.github.com/repos/util-linux/util-linux/tags | jq -r '.[0].name' | sed -e 's/^v//')
        echo "::debug::get util-linux version ${version}"
        echo "::set-output name=version::${version}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        build-args: UTIL_LINUX_VER=${{ steps.get_util_linux.outputs.version }}
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.get_util_linux.outputs.version }}
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY_IMAGE }}:${{ steps.get_util_linux.outputs.version }}
          ${{ env.REGISTRY_IMAGE }}:latest
        push: true
        registry: ${{ env.REGISTRY }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
